### ISSUE TITLE
угадай число

### ISSUE THREAD

**Issue by maulerant** [maxlashyn/python_games#23]
1. Ввести с консоли некоторое число n
2. В цикле пределожить угадать и ввести с консоли это число и сохранить его в переменную m
3. Проверить равняется ли m загаданному числу n
4. Вывести если меньше слово "меньше", если больше слово "больше", если равно слово "угадал"
5. посчитать количество попыток на угадывание числа
6. вывести на консоль посчитанное количество попыток

**Comment by maxlashyn** [comment]
реализовано, урок 1 задача 2
